networks:
  default:
    name: ${EXTERNAL_NETWORK}
    external: true

services:

  swiftcodesapi-docs-nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - SERVER_NAME=${SERVER_NAME}
      - APP_NAME=${APP_NAME}
      - APP_DOMAIN=${APP_DOMAIN}
    volumes:
      - ./:/var/www
      - ./config/docker/nginx/default.template:/etc/nginx/conf.d/default.template
    command: /bin/sh -c "envsubst '$${APP_NAME} $${SERVER_NAME}' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.swiftcodesapi-docs.rule=Host(`${SERVER_NAME}`,`www.${SERVER_NAME}`)'
